### ISSUE TITLE
Short description missing

### ISSUE THREAD

**Issue by dajare** [standardebooks/oliver-goldsmith_the-vicar-of-wakefield#1]
It looks like the short description, used in the RSS feed (and other places I suppose) is missing. There is just the dummy text, `DESCRIPTION`.

Check [`/epub/content.opf`, line 60][a].

Hope this helps.

[a]: https://github.com/standardebooks/oliver-goldsmith_the-vicar-of-wakefield/blob/8d31c3c819b9eab88a69d064d044f50502ab734d/src/epub/content.opf#L60

**Comment by acabal** [comment]
Thanks, this should be fixed now!
