### ISSUE TITLE
Modernize spelling "past" => "passed"

### ISSUE THREAD

**Issue by PLP-Consulting** [standardebooks/oliver-goldsmith_the-vicar-of-wakefield#2]
https://github.com/standardebooks/oliver-goldsmith_the-vicar-of-wakefield/blob/8f49eb2073d3c35409828668c2886ffe816867dd/src/epub/text/chapter-5.xhtml#L16

"The huntsman, who rode foremost, **past** us with great swiftness..."

**Comment by acabal** [comment]
Thanks!
