### ISSUE TITLE
extraneous comma

### ISSUE THREAD

**Issue by PLP-Consulting** [standardebooks/oliver-goldsmith_the-vicar-of-wakefield#3]
https://github.com/standardebooks/oliver-goldsmith_the-vicar-of-wakefield/blob/5a1651e292cd445dc8b12e56982325729b4243ec/src/epub/text/chapter-5.xhtml#L16

"...with a cheerful air they gave us**,** a favourite song of Dryden’s..."

**Comment by acabal** [comment]
Thanks!
