### ISSUE TITLE
modernize-spelling candidate: "alledging" => "alleging"

### ISSUE THREAD

**Issue by PLP-Consulting** [standardebooks/oliver-goldsmith_the-vicar-of-wakefield#4]
e.g.

https://github.com/standardebooks/oliver-goldsmith_the-vicar-of-wakefield/blob/5a1651e292cd445dc8b12e56982325729b4243ec/src/epub/text/chapter-11.xhtml#L26

**Comment by acabal** [comment]
Thanks!
