### ISSUE TITLE
"her's" => "hers"

### ISSUE THREAD

**Issue by PLP-Consulting** [standardebooks/oliver-goldsmith_the-vicar-of-wakefield#5]
https://github.com/standardebooks/oliver-goldsmith_the-vicar-of-wakefield/blob/5a1651e292cd445dc8b12e56982325729b4243ec/src/epub/text/chapter-23.xhtml#L14

"...even forgot my own pain in a concern for **her’s**."

**Comment by acabal** [comment]
Thanks!
